name: advanced1
channels:
  - conda-forge
dependencies:
  - folium=0.12*
  - jinja2=2.10*
  - osmnx=1.*
  - matplotlib
  - pandas=1.*
  - geopandas
  - descartes
  - shapely
  - poppler
  - numpy
  - pip:
    - alphashape